### ISSUE TITLE
Difficolta' nell'eseguire lo script

### ISSUE THREAD

**Issue by ElModdy** [moorada/lelouch#1]
Ciao,
non ho mai usato go e non ho idea di come si possa compilare ed eseguire un progetto.
Riusciresti a darmi qualche indicazione?
Grazie in anticipo e complimenti per lo script.

**Comment by moorada** [comment]
Ciao, se usi Linux puoi scaricare la release [qui](https://github.com/moorada/lelouch/releases/download/v1.0.0/lelouch_linux_amd64.zip).
Con Windows ho notato che non funziona bene e non ho in programma di fixarlo.
Non ho avuto modo di compilare e testare con Mac OS.

**Comment by ElModdy** [comment]
Grazie
